### ISSUE TITLE
Port freetype2.13.3

### ISSUE THREAD

**Issue by jor1178** [kisvegabor/lvgl#7421] opened 2024-12-06 09:11 UTC
### LVGL version

v9.2.2

### Platform

![2591f1ca0796eb76dd376bf4b72041e](https://github.com/user-attachments/assets/4186503b-3f4c-4239-a0da-805230a9f89b)

### What happened?

The emulator built with vscode ADAPTS to freetype, compiling times error, can not find the definition of these function interfaces。

**Comment by cheungxiongwei** [comment] 2024-12-06 10:51
It seems that your target_link_libraries target is wrong.
`lvgl` needs to link `freetype`, not the `main` target.
`target_link_libraries(lvgl PUBLIC freetype)`

If you include it as source code, you can use it like this, assuming the freetype source code is in the root directory.
```cmake
add_subdirectory(freetype)
target_link_libraries(lvgl PUBLIC freetype)
```

**Comment by jor1178** [comment] 2024-12-06 13:52
How to compile it into a dynamic library into the project, what should I do, do not want to use the source code

**Comment by jor1178** [comment] 2024-12-06 16:39
At present, the compilation has passed, but an error will be reported when running
![Uploading 46dd50744293b28f1457af1eec8c39b.png…]()

**Comment by jor1178** [comment] 2024-12-06 16:41
At present, the compilation has passed, but an error will be reported when runni
![Uploading d6955c5cff5f6e00e13d6ddb743afae.png…]()
ng

**Comment by jor1178** [comment] 2024-12-06 17:36
thanks

**Comment by kisvegabor** [comment] 2024-12-22 10:02
@jor1178 If the issue is resolved, please close it.

**Comment by jor1178** [comment] 2024-12-23 10:22
Thanks for answering. Closed

**Closed as completed** 2024-12-23 10:21 UTC
