### ISSUE TITLE
dropdown widget control has a bug！

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#7419] opened 2024-12-06 02:02 UTC
### LVGL version

v8.10 and v9.1

### Platform

I set the chinese dropdown list:
lv_dropdown_set_options(cur_dropdown_obj, "测试\n测试1\n测试2\n");

the select show is right,but the droplist is error,I have changed the chinese to utf8, but error show as:
![image](https://github.com/user-attachments/assets/dbbe243b-18cb-4f1e-8070-251f72203ff3)

### What happened?

the droplist also need to show right

**Comment by M1NGS** [comment] 2024-12-06 03:14
贴一下你的最小重现代码  Attach your code please.

**Comment by xinsuinizhuan** [comment] 2024-12-06 07:46
> 贴一下你的最小重现代码 Attach your code please.

    lv_obj_t* dd = lv_dropdown_create(lv_screen_active());
    lv_dropdown_set_options(dd, "test\n测试1\n测试2\n");

**Comment by cheungxiongwei** [comment] 2024-12-06 10:43
> > 贴一下你的最小重现代码 Attach your code please.
> 
> ```
> lv_obj_t* dd = lv_dropdown_create(lv_screen_active());
> lv_dropdown_set_options(dd, "test\n测试1\n测试2\n");
> ```

You also need to set the `lv_dropdown_get_list(dd)` object font.

`lv_obj_set_style_text_font(lv_dropdown_get_list(dd),font,LV_PART_MAIN);`

**Comment by uLipe** [comment] 2024-12-06 22:38
Please add the steps to reproduce the issue or please mention if the problem is not something that is not happen consistently.

**Comment by xinsuinizhuan** [comment] 2024-12-09 02:24
> lv_obj_set_style_text_font(lv_dropdown_get_list(dd),font,LV_PART_MAIN);

thank you, it is ok:

**Comment by M1NGS** [comment] 2024-12-09 09:46
> > lv_obj_set_style_text_font(lv_dropdown_get_list(dd),font,LV_PART_MAIN);
> 
> thank you, it is ok:

关闭issue啊，哥们儿， close issue please

**Comment by uLipe** [comment] 2024-12-10 19:49
Closing this one initially but if needed please feel free to reopen it.

**Closed as completed by uLipe** 2024-12-10 19:49 UTC
