### ISSUE TITLE
cpp  fatal error: ../../src/themes/lv_theme_private.h: No such file or directory

### ISSUE THREAD

**Issue by SalarAmirSalari** [kisvegabor/lvgl#6778] opened 2024-09-01 19:34 UTC
### LVGL version

9.1.0 - 9.3.0

### What happened?

I am encountering an issue with the LVGL library:
```
fatal error: ../../src/themes/lv_theme_private.h: No such file or directory
    1 | #include "../../src/themes/lv_theme_private.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Compilation error: exit status 1
```
Everything is configured as explained in the LVGL documentation (including ```lv_conf.h``` and ```User_Setup.h```). After checking the directory, the file exists, and I have no clue what is wrong (I am a beginner, btw).

I am getting this error on both Windows and Arch Linux, so I suspect it might be an issue with the library itself.

**Comment by amirmohammadrsa** [comment] 2024-09-02 09:21
Same issue

**Comment by C47D** [comment] 2024-09-02 22:04
What file is the error on?

**Comment by liamHowatt** [comment] 2024-09-03 00:47
Is it `examples/styles/lv_example_style_14.c`? It's a strange issue. I can't tell what's wrong. If you hadn't already tried on two different systems, I would've suggested doing a clean build.

**Comment by bladerunner09** [comment] 2024-09-03 12:43
Try correcting the file path.
#include "../../src/themes/lv_theme_private.h" -> #include "../src/themes/lv_theme_private.h"
or
#include "../../src/themes/lv_theme_private.h" -> #include "src/themes/lv_theme_private.h"

**Comment by liamHowatt** [comment] 2024-09-03 15:19
Good idea! Also try `#include "lvgl/src/themes/lv_theme_private.h"` How are you building/compiling your project?

**Comment by vwheeler63** [comment] 2024-09-03 15:40
Forgive me if I am missing something, but from `examples/styles/lv_example_style_14.c`
```
#include "../../src/themes/lv_theme_private.h"
```
is actually a correct path.  The only way to cause that error is if the file is actually not there....  This would not be hard to have happen since the file was only added a month ago.  @SalarAmirSalari , when you look in your local `lvgl/src/themes` directory, is the `lv_theme_private.h` file actually there?  If not, then you probably have a "snapshot" of LVGL before this file was created.

- Are you working from your LVGL fork (which does have the file)?  Or directly cloned from `lvgl/lvgl`?
- Is it in your local `lvgl/src/themes/` directory?

**Comment by JeroenRegtien** [comment] 2024-09-03 19:07
I had the same problem. On my Mac OSC installation I had to edit the "example_style_14.c" file and insert an extra "../" in the path for "lv_theme_private.h". The error disappeared but then a new compilation error occurred for file "lv_example_scale_7.c". Same issue here, add an extra "../" in the path of header file "lvgl_private.h".

My lvgl demo for the gigadisplay shield then compiles again, but displays garbage on the screen. I am concerned the latest lvgl library release (I was using 9.2.0) is corrupt or hasn't been checked properly before release.

I reverted back to 9.0.0 and then had no compilation nor run time problems... I then moved to 9.1.0 and this worked fine too.
So my suggestion is to avoid 9.2.0 until these errors are fixed. I have however no idea how to find that out...

**Comment by liamHowatt** [comment] 2024-09-04 03:21
As vwheeler63 said, the most important question is: is the file in the directory it should be in? If it's not, are you using some kind of fork that was only partially updated to v9.3?

**Comment by sanimalp** [comment] 2024-09-06 07:16
this would only happen if you copied examples into src? right? 

The paths are correct in the files you are referring to, in the context of this repository. `example_style_14.c` and `lv_example_scale_7.c` have correct paths from the root of the repository, but if you copied your example folder into source, it would cause these problems. Your options are: remove the example folder from source, or fix the paths if you intend to keep the folder in src. 

here is a prominent tutorial that suggests the copy of examples into src, as a possible source for this bug https://randomnerdtutorials.com/lvgl-cheap-yellow-display-esp32-2432s028r/

**Comment by liamHowatt** [comment] 2024-09-09 21:29
Thanks sanimalp.

You can use the examples by compiling them where they are and calling `lv_example_style_14()` from your code or you can move or repurpose the examples of course, but the include paths may need to be updated, as sanimalp said.

**Comment by LuckierBread** [comment] 2024-09-12 07:07
This happened to me because my examples and demos folders were copied into my src folder. they are normally outside the src. I did this because I needed to access lv_demos.h but I found it better to access it via `#include <../demos/lv_demos.h>`
It saved me form having to rewrite a bunch of other files.

**Comment by ouening** [comment] 2024-09-14 07:48
Same issue in vesion 9.2

**Comment by FeeJayHere** [comment] 2024-10-03 07:23
Hello, I would like to add some info to this:
The problem is happening when using Arduino IDE
When installing lvgl version 9.2 from library manager, after configuring TFT_eSPI and lv_conf.h, LVGL docs have a note here: https://docs.lvgl.io/master/integration/framework/arduino.html#use-the-examples-and-demos to copy examples and demos folders to src. After copying these folders, the error mentioned appear.
I think that the docs for master (latest) should be updated or code changed to fix that

**Comment by kissa96** [comment] 2024-10-24 08:11
Hi, is this still a valid and open issue?

**Comment by kisvegabor** [comment] 2024-10-30 14:56
Closing it in lack of feedback. Let us know if the issue is still ongoing.

**Comment by razarahil** [comment] 2024-11-19 07:19
I'm still getting this error when compiling.

**Comment by qq71680264** [comment] 2024-11-21 11:45
> Closing it in lack of feedback. Let us know if the issue is still ongoing.

Arduino IDE 2.3.3
ESP32 Package 3.0.7
LVGL library 9.2.2

Still getting this error when compiling.

**Comment by kisvegabor** [comment] 2024-11-27 08:12
Hey,
I've check this issue again and found a solution, please test it with https://github.com/lvgl/lvgl/pull/7366

**Comment by minou65** [comment] 2024-11-30 17:37
Hi I have the same issue, also with this mr
> Hey, I've check this issue again and found a solution, please test it with #7366

**Comment by kisvegabor** [comment] 2024-12-02 22:23
Oh, thank! Maybe with this? https://github.com/lvgl/lvgl/pull/7397 :crossed_fingers: 

@fbiego Could you also try if https://github.com/lvgl/lvgl/pull/7397 can be compiled in Arduino?

**Comment by fbiego** [comment] 2024-12-03 09:00
I have tried compiling #7397 in Arduino. @kisvegabor 

### Without copying the demos to src
`#include <../demos/lv_demos.h> /* include demos */`
It results in an error
> undefined reference to lv_demo_ebike


### When demos is copied to src

`#include <demos/lv_demos.h> /* include demos */`

all files in demos folder with `../../src/` needs to be changed to `../../`
eg
`#include "../../src/lvgl_private.h"`
to
`#include "../../lvgl_private.h"`

The second option compiles successfully

**Comment by kisvegabor** [comment] 2024-12-03 10:22
Thank you @fbiego. I've updated the PR. I wonder if there is a way to add an Arduino build test to our CI. Maybe with Arduino CLI?

**Comment by fbiego** [comment] 2024-12-03 12:43
> Thank you @fbiego. I've updated the PR. I wonder if there is a way to add an Arduino build test to our CI. Maybe with Arduino CLI?

I'm not familiar with Arduino CLI, I'll research on that

**Comment by minou65** [comment] 2024-12-04 22:04
Hi @kisvegabor 
> Oh, thank! Maybe with this? #7397 🤞
> 
> @fbiego Could you also try if #7397 can be compiled in Arduino?

I can confirm that with this MR I do not recive anymore this errors. I am always not able to build the examples from waveshare. But that is an other story

**Comment by kisvegabor** [comment] 2024-12-05 20:01
Thank you for the feedback. The PR is merged so I close this issue. 🎉

**Closed as completed by kisvegabor** 2024-12-05 20:01 UTC

**Comment by BoraMD** [comment] 2025-02-07 11:27
I got similar error on 
MacOS 15.1.1
Arduino IDE 2.3.4
LVGL 9.2.0
ESP32 3.1.1 

When I just try LVGL_Arduino sketch I can compile and it shows Hello Arduino text.
However if I try example or demo it gives the same error:
/Users/boramutludogan/Documents/Arduino/libraries/lvgl/src/examples/styles/lv_example_style_14.c:1:10: fatal error: ../../src/themes/lv_theme_private.h: No such file or directory
    1 | #include "../../src/themes/lv_theme_private.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

There is lv_theme_private.h file in that directory.
Tried changing the path according to above suggestions but it gives more errors.

**Comment by BoraMD** [comment] 2025-02-07 14:14
Also I managed to make demo work. Copied demos folder to src and tried lv_demo_widgets(); and enabled demo widgets on lv_conf it works.

**Comment by Mr-Newlove** [comment] 2025-03-26 21:56
I am still having this issue on v9.2.2.

https://forum.lvgl.io/t/wt32-sc01-plus-arduino-v9-widget-demo-struggle/20641

my current arduino code:

```
#include <LovyanGFX.hpp>
//#include "Libraries\lvgl\9.2.2\lvgl\src\themes\lv_theme_private.h"
#include <lvgl.h>
//#include <demos/lv_demos.h>
//#include <examples/lv_examples.h>
#include <SPI.h>


#define screenWidth 480
#define screenHeight 320

class LGFX : public lgfx::LGFX_Device
{
    lgfx::Panel_ST7796      _panel_instance;
    lgfx::Bus_Parallel8 _bus_instance;   // 8-bit parallel bus instance (ESP32 only)
    lgfx::Light_PWM     _light_instance;
    lgfx::Touch_FT5x06           _touch_instance; // FT5206, FT5306, FT5406, FT6206, FT6236, FT6336, FT6436
public:
    LGFX(void);
};


LGFX::LGFX(void)
{
    { // Bus config for LCD
        auto cfg = _bus_instance.config();    // inital bus configuration data structure
        // 8 bit parallel
              //cfg.i2s_port = I2S_NUM_0;     // Select the I2S port to use (I2S_NUM_0 or I2S_NUM_1) (Use the I2S LCD mode of ESP32)
        cfg.freq_write = 20000000;    // Bus transmission clock (maximum 20MHz, rounded to an integer division of 8MHz?)
        cfg.pin_wr = 47;              // WR Pin
        cfg.pin_rd = -1;              // RD Pin
        cfg.pin_rs = 0;              // RS(D/C) Pin
        cfg.pin_d0 = 9;              // D0 Pin
        cfg.pin_d1 = 46;              // D1 Pin
        cfg.pin_d2 = 3;              // D2 Pin
        cfg.pin_d3 = 8;              // D3 Pin
        cfg.pin_d4 = 18;              // D4 Pin
        cfg.pin_d5 = 17;              // D5 Pin
        cfg.pin_d6 = 16;              // D6 Pin
        cfg.pin_d7 = 15;              // D7 Pin
        _bus_instance.config(cfg);    // Set this config to the bus instance
        _panel_instance.setBus(&_bus_instance);      // Assign this bus to the panel
    }

    { // LCD control settings
        auto cfg = _panel_instance.config();    // Intial LCD configuration data structure

        cfg.pin_cs = -1;  // CS pin, (-1 to disable for parallel interface)
        cfg.pin_rst = 4;  // RST pin, (-1 to disable for parallel interface)
        cfg.pin_busy = -1;  // BUSY pin, (-1 to disable for parallel interface)

        // General default values for LCD, you may needc to comment some out to get it working

        cfg.panel_width = 320;  // LCD pixel width
        cfg.panel_height = 480;  // LCD pixel height
        cfg.offset_x = 0;  // LCD pixel ofset X(width)
        cfg.offset_y = 0;  // LCD pixel ofset Y(height)
        cfg.offset_rotation = 0;  // LCD rotation 0~7 (4~7 are upside down)
        cfg.dummy_read_pixel = 8;  // Number of dummy reads bits before first pixel read
        cfg.dummy_read_bits = 1;  // Number of dummy read bits before reading non-pixel data
        cfg.readable = true;  // Set to true if data can be read
        cfg.invert = true;  // Panel inverted
        cfg.rgb_order = false;  // Set to true if panel Red and Blue are swapped
        cfg.dlen_16bit = false;  // Set to true if panel transmists data in 16 bit units via parallel or SPI
        cfg.bus_shared = true;  // Set to true of bus is shared with an SD card(so bus can preform drawJpGFile etc)

        // set the following only if the display is misaligned when using a driver with a variable number of pixels, such as ST7735 or ILI9163
        //    cfg.memory_width     =   240;  // Maximum width supported by the driver IC
        //    cfg.memory_height    =   320;  // Maximum height supported by driver IC

        _panel_instance.config(cfg);
    }

    //*
    { // Backlight control
        auto cfg = _light_instance.config();    // initial backlight data structure

        cfg.pin_bl = 45;              // Pin used for backlight PWM
        cfg.invert = false;           // Set to true if backlight is inverted
        cfg.freq = 44100;           // Backlight PWM Frequency
        cfg.pwm_channel = 7;          // Internal PWM channel number

        _light_instance.config(cfg);
        _panel_instance.setLight(&_light_instance);  // Attach backlight to the LCD
    }

    { // Touch screen config
        auto cfg = _touch_instance.config();

        cfg.x_min = 0;    // Raw touch screen min X value
        cfg.x_max = 319;  // Raw touch Screen max X value
        cfg.y_min = 0;    // Raw touch screen min Y value
        cfg.y_max = 479;  // Raw touch screen max Y value
        cfg.pin_int = 7;   // INT pin number
        cfg.bus_shared = true; // If bus is shared with any other devices set to true
        cfg.offset_rotation = 0; // Used to correct orientation of the touch screen to match the LCD, values 0-7
        // I2C接続の場合
        cfg.i2c_port = 1;      // Select which internal I2C port to use
        cfg.i2c_addr = 0x38;   // I2C address
        cfg.pin_sda = 6;     // SDA Pin
        cfg.pin_scl = 5;     // SCL Pin
        cfg.freq = 400000;     // I2C clock speed

        _touch_instance.config(cfg);
        _panel_instance.setTouch(&_touch_instance); // Attached the touchscreen and the LCD instance
    }
    //*/
    setPanel(&_panel_instance); // Set Panel Instance
};
const unsigned int lvBufferSize = screenWidth * screenHeight / 10 * (LV_COLOR_DEPTH / 8);
uint8_t lvBuffer[lvBufferSize];

LGFX tft;

void set_up_tft(void) {
    tft.begin();
    tft.setRotation(3);
    tft.setBrightness(255);
}

void flush(lv_display_t* display, const lv_area_t* area, unsigned char* data)
{
    uint32_t w = lv_area_get_width(area);
    uint32_t h = lv_area_get_height(area);
    lv_draw_sw_rgb565_swap(data, w * h);
    tft.pushImage(area->x1, area->y1, w, h, (uint16_t*)data);
    lv_display_flush_ready(display);
}

void my_touch_read(lv_indev_t* indev_driver, lv_indev_data_t* data)
{
    uint16_t touchX, touchY;
    bool touched = tft.getTouch(&touchX, &touchY);
    if (!touched) { data->state = LV_INDEV_STATE_REL; }
    else {
        data->state = LV_INDEV_STATE_PR;
        data->point.x = touchX;
        data->point.y = touchY;
    }
}

void setup() {
    Serial.begin(115200);


    //pinMode(BL_PWM, OUTPUT);
    //analogWrite(BL_PWM, 200);


    set_up_tft();

    lv_init();
    static auto* display = lv_display_create(screenWidth, screenHeight);
    lv_display_set_color_format(display, LV_COLOR_FORMAT_RGB565);
    lv_display_set_flush_cb(display, flush);
    lv_display_set_buffers(display, lvBuffer, nullptr, lvBufferSize, LV_DISPLAY_RENDER_MODE_PARTIAL);

    static auto* lvInput = lv_indev_create();
    lv_indev_set_type(lvInput, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(lvInput, my_touch_read);

    lv_example_chart_5();


}

void loop() {
    lv_timer_handler();
    lv_tick_inc(5);
    delay(5);
}
void lv_example_chart_5(void)
{
    /*Create a chart*/
    lv_obj_t* chart = lv_chart_create(lv_screen_active());
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);   /*Show lines and points too*/
    lv_obj_set_size(chart, 200, 150);
    lv_obj_set_style_pad_all(chart, 0, 0);
    lv_obj_set_style_radius(chart, 0, 0);
    lv_obj_center(chart);

    lv_chart_set_div_line_count(chart, 5, 7);

    lv_obj_add_event_cb(chart, draw_event_cb, LV_EVENT_DRAW_TASK_ADDED, NULL);
    lv_obj_add_flag(chart, LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS);

    lv_chart_series_t* ser = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);

    uint32_t i;
    for (i = 0; i < 10; i++) {
        lv_chart_set_next_value(chart, ser, (int32_t)lv_rand(10, 80));
    }
}

static void draw_event_cb(lv_event_t* e)
{
    lv_draw_task_t* draw_task = lv_event_get_draw_task(e);
    lv_draw_dsc_base_t* base_dsc = (lv_draw_dsc_base_t*)lv_draw_task_get_draw_dsc(draw_task);

    if (base_dsc->part == LV_PART_ITEMS && lv_draw_task_get_type(draw_task) == LV_DRAW_TASK_TYPE_LINE) {
        add_faded_area(e);

    }
    /*Hook the division lines too*/
    if (base_dsc->part == LV_PART_MAIN && lv_draw_task_get_type(draw_task) == LV_DRAW_TASK_TYPE_LINE) {
        hook_division_lines(e);
    }
}

static void add_faded_area(lv_event_t* e)
{
    lv_obj_t* obj = lv_event_get_target_obj(e);
    lv_area_t coords;
    lv_obj_get_coords(obj, &coords);

    lv_draw_task_t* draw_task = lv_event_get_draw_task(e);
    lv_draw_dsc_base_t* base_dsc = (lv_draw_dsc_base_t*)lv_draw_task_get_draw_dsc(draw_task);

    const lv_chart_series_t* ser = lv_chart_get_series_next(obj, NULL);
    lv_color_t ser_color = lv_chart_get_series_color(obj, ser);

    /*Draw a triangle below the line witch some opacity gradient*/
    lv_draw_line_dsc_t* draw_line_dsc = (lv_draw_line_dsc_t*)lv_draw_task_get_draw_dsc(draw_task);
    lv_draw_triangle_dsc_t tri_dsc;

    lv_draw_triangle_dsc_init(&tri_dsc);
    tri_dsc.p[0].x = draw_line_dsc->p1.x;
    tri_dsc.p[0].y = draw_line_dsc->p1.y;
    tri_dsc.p[1].x = draw_line_dsc->p2.x;
    tri_dsc.p[1].y = draw_line_dsc->p2.y;
    tri_dsc.p[2].x = draw_line_dsc->p1.y < draw_line_dsc->p2.y ? draw_line_dsc->p1.x : draw_line_dsc->p2.x;
    tri_dsc.p[2].y = LV_MAX(draw_line_dsc->p1.y, draw_line_dsc->p2.y);
    tri_dsc.grad.dir = LV_GRAD_DIR_VER;

    int32_t full_h = lv_obj_get_height(obj);
    int32_t fract_uppter = (int32_t)(LV_MIN(draw_line_dsc->p1.y, draw_line_dsc->p2.y) - coords.y1) * 255 / full_h;
    int32_t fract_lower = (int32_t)(LV_MAX(draw_line_dsc->p1.y, draw_line_dsc->p2.y) - coords.y1) * 255 / full_h;
    tri_dsc.grad.stops[0].color = ser_color;
    tri_dsc.grad.stops[0].opa = (lv_opa_t)(255 - fract_uppter);
    tri_dsc.grad.stops[0].opa = 255 - fract_uppter;
    tri_dsc.grad.stops[0].frac = 0;
    tri_dsc.grad.stops[1].color = ser_color;
    tri_dsc.grad.stops[1].opa = (lv_opa_t)(255 - fract_lower);
    tri_dsc.grad.stops[1].frac = 255;

    lv_draw_triangle(base_dsc->layer, &tri_dsc);

    /*Draw rectangle below the triangle*/
    lv_draw_rect_dsc_t rect_dsc;
    lv_draw_rect_dsc_init(&rect_dsc);
    rect_dsc.bg_grad.dir = LV_GRAD_DIR_VER;
    rect_dsc.bg_grad.stops[0].color = ser_color;
    rect_dsc.bg_grad.stops[0].frac = 0;
    rect_dsc.bg_grad.stops[0].opa = (lv_opa_t)(255 - fract_lower);
    rect_dsc.bg_grad.stops[1].color = ser_color;
    rect_dsc.bg_grad.stops[1].frac = 255;
    rect_dsc.bg_grad.stops[1].opa = 0;

    lv_area_t rect_area;
    rect_area.x1 = (int32_t)draw_line_dsc->p1.x;
    rect_area.x2 = (int32_t)draw_line_dsc->p2.x - 1;
    rect_area.y1 = (int32_t)LV_MAX(draw_line_dsc->p1.y, draw_line_dsc->p2.y) - 1;
    rect_area.y2 = (int32_t)coords.y2;
    lv_draw_rect(base_dsc->layer, &rect_dsc, &rect_area);
}

static void hook_division_lines(lv_event_t* e)
{
    lv_draw_task_t* draw_task = lv_event_get_draw_task(e);
    lv_draw_dsc_base_t* base_dsc = (lv_draw_dsc_base_t*)lv_draw_task_get_draw_dsc(draw_task);
    lv_draw_line_dsc_t* line_dsc = (lv_draw_line_dsc_t*)lv_draw_task_get_draw_dsc(draw_task);

    /*Vertical line*/
    if (line_dsc->p1.x == line_dsc->p2.x) {
        line_dsc->color = lv_palette_lighten(LV_PALETTE_GREY, 1);
        if (base_dsc->id1 == 3) {
            line_dsc->width = 2;
            line_dsc->dash_gap = 0;
            line_dsc->dash_width = 0;
        }
        else {
            line_dsc->width = 1;
            line_dsc->dash_gap = 6;
            line_dsc->dash_width = 6;
        }
    }
    /*Horizontal line*/
    else {
        if (base_dsc->id1 == 2) {
            line_dsc->width = 2;
            line_dsc->dash_gap = 0;
            line_dsc->dash_width = 0;
        }
        else {
            line_dsc->width = 2;
            line_dsc->dash_gap = 6;
            line_dsc->dash_width = 6;
        }

        if (base_dsc->id1 == 1 || base_dsc->id1 == 3) {
            line_dsc->color = lv_palette_main(LV_PALETTE_GREEN);
        }
        else {
            line_dsc->color = lv_palette_lighten(LV_PALETTE_GREY, 1);
        }
    }
}
```

with error:
```The lvgl library encountered an unknown path resolve error.Z*: 1:10: fatal error: ../../src/themes/lv_theme_private.h: No such file or directory```

I have copied the example and demo files into scr. I have tried many different alternative locations for the lv_theme_private.h file. I am not sure what do do.

**Comment by TechOverflow** [comment] 2025-05-22 02:20
In `lvgl/src/examples/styles/lv_example_style_14.c` change:
from `#include "../../src/themes/lv_theme_private.h"`
to `#include "../../themes/lv_theme_private.h"`

In `lvgl/src/examples/widgets/scale/lv_example_scale_7.c` change:
from `#include "../../../src/lvgl_private.h"`
to `#include "../../../lvgl_private.h"`

The `src/` makes no sense as these examples are already in `src/` when you copy `examples/` into `src/` as per the installation instructions.

There may be other bad links in other files. These were just the ones I encountered in the example I was trying to compile.
