### ISSUE TITLE
Color value in text

### ISSUE THREAD

**Issue by xaowang96** [kisvegabor/lvgl#5573] opened 2024-02-02 07:24 UTC
### Introduce the problem

In V8, we can use #color to set color of text, like this:
`lv_label_set_text(label, "#FFFFF white ##FF0000 red #");`
It is very convenient to be used to set different color in a text. But in v9, there is no this feature. 

### Proposal

Maybe We should add this feature back into V9.

**Comment by PGNetHun** [comment] 2024-02-02 08:12
Duplicate of https://github.com/lvgl/lvgl/issues/5468

**Comment by kisvegabor** [comment] 2024-02-02 16:51
Being discussed in #5352.

**Closed as completed by kisvegabor** 2024-02-02 16:51 UTC
Labels: 🔁 Duplicated
