### ISSUE TITLE
lv_demo_widgets example in windows, get stuck and break!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6217] opened 2024-05-13 01:44 UTC
### LVGL version

v9.1.1

### What happened?

when i run the lv_demo_widgets and move the left or right in tab, when mve the half of thme, the i get stuck, then when i close the frame, it break!
i move right, and stop half of analyticks tab, the i can't operate any of them, it get stuck.
![图片](https://github.com/lvgl/lvgl/assets/40679769/06182a9e-e810-4897-8911-141ecb426552)
then when i close the frame, it break:
![图片](https://github.com/lvgl/lvgl/assets/40679769/24c87304-beb5-47c2-bee3-9519c2eddbf9)

**Comment by liamHowatt** [comment] 2024-05-13 14:55
More likely than not, the display closing issue on Windows is #6059 which is still an open issue where we have discussed a solution to in that issue.

For the tabs getting stuck, I tried it out and I think it's because the Windows environment doesn't track the mouse after it leaves the window bounds while you're dragging. [This](https://github.com/lvgl/lvgl/blob/a36816ad768eda32e4714d94e91a1fa5785e0c15/src/drivers/windows/lv_windows_input.c#L297-L348) is the relevant logic. I could not fix it by commenting out [this part](https://github.com/lvgl/lvgl/blob/a36816ad768eda32e4714d94e91a1fa5785e0c15/src/drivers/windows/lv_windows_input.c#L320-L331).

**Comment by xinsuinizhuan** [comment] 2024-05-14 00:51
> More likely than not, the display closing issue on Windows is #6059 which is still an open issue where we have discussed a solution to in that issue.
> 
> For the tabs getting stuck, I tried it out and I think it's because the Windows environment doesn't track the mouse after it leaves the window bounds while you're dragging. [This](https://github.com/lvgl/lvgl/blob/a36816ad768eda32e4714d94e91a1fa5785e0c15/src/drivers/windows/lv_windows_input.c#L297-L348) is the relevant logic. I could not fix it by commenting out [this part](https://github.com/lvgl/lvgl/blob/a36816ad768eda32e4714d94e91a1fa5785e0c15/src/drivers/windows/lv_windows_input.c#L320-L331).
> 
> Can you use full screen for your use case?
> 
> cc @MouriNaruto

when i use full screen, have this problem:
![图片](https://github.com/lvgl/lvgl/assets/40679769/94d9d933-1c6a-46db-aae2-258a8533f3bd)

**Comment by xinsuinizhuan** [comment] 2024-05-14 00:55
For the tabs getting stuck, i think is the tab problem, i could not move the whole tab onece, so it stop in half, then could not operate any, it is so bad, whe i move he 3/4 tab, could let tab move the end by self?

**Comment by C47D** [comment] 2024-05-15 02:58
Hi,

I'm able to replicate the needle issue, I'll take a look at it.
![image](https://github.com/lvgl/lvgl/assets/11037705/aa7a36d6-1b2b-4c01-829a-a879646c1b61)

**Comment by C47D** [comment] 2024-05-20 03:52
Hi @kisvegabor ,

I'm checking the needle issue and it's being created as a separated object to the `scale3` scale widget in the widgets demo (the Mbps and value labels are also created as `scale3` childs):
```c
    LV_IMAGE_DECLARE(img_demo_widgets_needle);
    lv_obj_t * needle = lv_image_create(scale3);
    lv_image_set_src(needle, &img_demo_widgets_needle);
    lv_image_set_pivot(needle, 3, 4);
    lv_obj_align(needle, LV_ALIGN_CENTER, 47, -2);

    lv_obj_t * mbps_label = lv_label_create(scale3);
    lv_label_set_text(mbps_label, "-");
    lv_obj_add_style(mbps_label, &style_title, 0);

    lv_obj_t * mbps_unit_label = lv_label_create(scale3);
    lv_label_set_text(mbps_unit_label, "Mbps");

    lv_anim_init(&a);
    lv_anim_set_values(&a, 10, 60);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_exec_cb(&a, scale3_anim_cb);
    lv_anim_set_var(&a, scale3);
    lv_anim_set_duration(&a, 4100);
    lv_anim_set_playback_duration(&a, 800);
    lv_anim_start(&a);

    lv_obj_align(mbps_label, LV_ALIGN_TOP_MID, 10, lv_pct(55));
    lv_obj_align_to(mbps_unit_label, mbps_label, LV_ALIGN_OUT_RIGHT_BOTTOM, 10, 0);
```

Is there a way to inform those childs the parent position has been updated, so their position is also updated accordingly? I hope this is the root cause for this needle issue, any thoughts @liamHowatt ?

**Comment by kisvegabor** [comment] 2024-05-22 11:43
The issue is happening because the scale has 100% width, but it's always a circle, but the needle doesn't know about it. It's always aligned to the center.
 
![scale](https://github.com/lvgl/lvgl/assets/7599318/94c0d4d1-8f8f-4bce-a992-4201cff9aeda)

`LV_EVENT_SIZE_CHANGED` should be fired when the scale's size changes.

**Comment by C47D** [comment] 2024-05-22 20:27
Seems to me that the "Mbps" label is always correct and the needle and value label is tracking the container size change, isn't?

**Comment by C47D** [comment] 2024-05-23 05:16
@kisvegabor When setting an image position we're positioning the top-left corner or the image pivot?

I tried adding the following event callback to the scale3 resizing and the needle is not really on the scale center. I was expecting that because I'm getting the scale coordinates and dividing it by 2 on each axis.

```c
static void scale3_size_changed_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_SIZE_CHANGED) {
    	lv_area_t scale_coords;
    	lv_point_t scale_center;
    	lv_obj_get_coords(scale3, &scale_coords);
    	scale_center.x = (scale_coords.x2 - scale_coords.x1) / 2U;
    	scale_center.y = (scale_coords.y2 - scale_coords.y1) / 2U;
     	lv_obj_align(needle, LV_ALIGN_CENTER, scale_center.x, scale_center.y);
    }
}
```
Notice the needle at the bottom right side of the scale container.
![image](https://github.com/lvgl/lvgl/assets/11037705/3f8b12df-aa78-493b-b2b3-d7c56c6577f4)

**Comment by liamHowatt** [comment] 2024-05-23 23:45
@C47D I think I was able to get it. It might not be perfect but I hope it helps get you unstuck. The main issues were:

- The scale is visually "square" despite the scale obj having rectangular dimensions so the center is `min(x, y)/2`.
- Align to the top-left instead of center because you're computing an offset relative to the scale's top-left corner.

```c
static void scale3_size_changed_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_SIZE_CHANGED) {
        int32_t scale_width = lv_obj_get_width(scale3);
        int32_t scale_height = lv_obj_get_height(scale3);
        int32_t minor_dimension = LV_MIN(scale_width, scale_height);
        int32_t minor_dimension_half = minor_dimension / 2;
        /* Update needle position */
        lv_obj_align(needle, LV_ALIGN_TOP_LEFT, minor_dimension_half, minor_dimension_half);

        /* Update labels position */
        if (mbps_label) {
            lv_obj_align(mbps_label, LV_ALIGN_TOP_LEFT, minor_dimension_half, minor_dimension * 55 / 100);
        }
        if (mbps_label && mbps_unit_label) {
            lv_obj_align_to(mbps_unit_label, mbps_label, LV_ALIGN_OUT_RIGHT_BOTTOM, 10, 0);
        }
    }
}
```

**Comment by C47D** [comment] 2024-05-23 23:57
Hi,

You're right, thanks for the explanation. I totally missed the scale being an rectangle when the window gets bigger, I can see it now on @kisvegabor video/gif.

It seems to be working:
![image](https://github.com/lvgl/lvgl/assets/11037705/8aa116d3-06c2-4479-a29d-39de9f7f94f8)

@liamHowatt Do you want to send the pull request to fix that issue or do you want me to send it?

**Comment by liamHowatt** [comment] 2024-05-24 00:06
I can send it since I basically just need to commit and push. :+1:

**Comment by xinsuinizhuan** [comment] 2024-05-27 01:33
newest code not fixed?
![图片](https://github.com/lvgl/lvgl/assets/40679769/d2c98ab0-d3e2-47fe-a2d3-9e1fa9246934)

the meter is not middle, and the point is dissociate

**Comment by C47D** [comment] 2024-05-27 23:43
The fix haven't been merged yet

**Comment by C47D** [comment] 2024-06-05 17:19
Fix was merged, can you update your code base?

**Comment by kisvegabor** [comment] 2024-06-20 17:54
I close this issue because there was no activity here for a while.

If you have remarks about this topic feel free to comment here and reopen the issue.

**Closed as completed by kisvegabor** 2024-06-20 17:54 UTC
